force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <description>Store the Date &amp; Time details when the Error Occurred</description>
    <label>Log</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <description>Stores the Complete Stack Track about the Problem</description>
    <label>Log Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <description>The Name of Either Apex Class or Apex Trigger</description>
    <label>Process Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogRecordInsertTest.cls
@isTest
public class ErrorLogRecordInsertTest {
    @isTest
    static void insertErrorLogTest(){
        Test.startTest();
        String processName = 'Process 1';
        String logDetails = 'Error occurred during processing';
        ErrorLogRecordInsert.insertErrorLog(logDetails, processName);
        List<Error_Log__c> logs = [SELECT Process_Name__c, Log__c, Log_Details__c FROM Error_Log__c WHERE Process_Name__c = :processName];
        System.assertEquals(1, logs.size());
        Error_Log__c log = logs[0];
        System.assertEquals(processName, log.Process_Name__c);
        System.assertEquals(logDetails, log.Log_Details__c);
        Test.stopTest();
    }

}