force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Please provide the Email.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Please the provide the phone</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Please provide the end date.</description>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Fequency__c.field-meta.xml
<CustomField>
    <fullName>Fequency__c</fullName>
    <description>Is the event will occur daily or weekly.</description>
    <label>Fequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Recurring__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the Event will be Live?</description>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Please provide the date .</description>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Please provide the email</description>
    <inlineHelpText>Please provide the email.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Please provide the Phone number</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/EventAttendeeTriggerTest.cls
@isTest
private class EventAttendeeTriggerTest {
    @isTest
    static void attendeeEmailSendTest() {
        // Setup test data
        Event_Organizer__c org = new Event_Organizer__c(
            Name = 'Test Org',
            Phone__c = '1234567890',
            Email__c = 'ashutosh.singh@mirketa.com'
        );
        insert org;
        Event__c evt = new Event__c(
            Name__c = 'Test Event',
            Event_Organizer__c = org.Id,
            Event_Type__c = 'Virtual',
            Fequency__c = 'Weekly',
            Max_Seats__c = 100,
            Recurring__c = true,
            Live__c = true,
            Start__c = System.now().addDays(1),
            End__c = System.now().addDays(3)
        );
        insert evt;
        Attendee__c att = new Attendee__c(
            Name = 'Test Attendee',
            Email__c = 'aman.kumar@mirketa.com',
            Phone__c = '1234567890'
        );
        insert att;
        Event_Attendee__c evtAtt = new Event_Attendee__c(
            Event__c = evt.Id,
            Attendee__c = att.Id
        );
        insert evtAtt;
        
        // Call the method being tested
        Test.startTest();
        EventAttendeeTriggerHandler.attendeeEmailSend(new List<Event_Attendee__c>{ evtAtt });
        Test.stopTest();
        
        // Verify that an email was sent
        System.assertEquals(1, Limits.getEmailInvocations());
    }
}