force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Speaker__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Please provide the email.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EventOrganizerPost.cls
@RestResource(urlMapping='/v1/EventOrganizerPost/')
global  class EventOrganizerPost{
        @httpPost
        global static String doPostMethod(String Name, String email, String phone, String company){
        try  
        {
        Speaker__c spkr= new Speaker__c(Name =Name, Email__c = email, Phone__c = phone, Company__c = company);      
        insert spkr;
        return '200';
        }
        catch(Exception e){
        return '400';
        }

    }
}