force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Please provide the date .</description>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Please provide the email</description>
    <inlineHelpText>Please provide the email.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EventOrganizerWeb.cls
@RestResource(urlMapping='/v1/EventOrganizerWeb/')
global class EventOrganizerWeb {
@httpGet
global static List<EventWrapper> doGetMethod(){
    List<EventWrapper> eventWrappers = new List<EventWrapper>();
    List<Event__c> events = [SELECT Name__c, Start__c, Max_Seats__c,Event_Organizer__r.Name , Event_Organizer__r.Email__c FROM Event__c];
 for (Event__c event : events) {
    EventWrapper eventWrapper = new EventWrapper();
    eventWrapper.event = new Event__c();
    eventWrapper.event.Name__c = event.Name__c;
    eventWrapper.event.Start__c = event.Start__c;
    eventWrapper.event.Max_Seats__c = event.Max_Seats__c;
    eventWrapper.event_organizer = new Event_Organizer__c();
    eventWrapper.event_organizer.Name = event.Event_Organizer__r.Name;
    eventWrapper.event_organizer.Email__c = event.Event_Organizer__r.Email__c;
    eventWrappers.add(eventWrapper);
 }
 return eventWrappers;
 }
 // Wrapper class for events
global class EventWrapper {
    global Event__c event;
    global Event_Organizer__c event_organizer;
 }
}