force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Organizer__c.field-meta.xml
<CustomField>
    <fullName>Event_Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Please provide the date .</description>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Organizer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Please provide the email</description>
    <inlineHelpText>Please provide the email.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/EventOrganizerWebTest.cls
@isTest
public class EventOrganizerWebTest {
    static testMethod void testGetMethod(){
        Event__c evt =new Event__c();
        Event_Organizer__c evtOrg = new Event_Organizer__c();
        evt.Name__c ='Test Event Web Service 1';
        evt.Start__c=datetime.newInstance(2024,9,15,12,30,0);
        evtOrg.Email__c='abc@avc.com';
        insert evtOrg;
        evt.Event_Organizer__c=evtOrg.Id;
        insert evt;
        RestRequest req =new RestRequest();
        req.requestURI='/services/apexrest/v1/EventOrganizerWeb/';
        req.httpMethod='GET';
        RestContext.request=req;
        Test.startTest();
        List<EventOrganizerWeb.EventWrapper> evnt = EventOrganizerWeb.doGetMethod();
        Test.stopTest();
        System.assert(evnt!=null);
        System.assertEquals('Test Event Web Service 1', evnt.get(0).event.Name__c);


    
    }

}