force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End__c.field-meta.xml
<CustomField>
    <fullName>End__c</fullName>
    <description>Please provide the end date.</description>
    <label>End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the Event will be Live?</description>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Please provide the date .</description>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/DeleteEventBatchTest.cls
@isTest
private class DeleteEventBatchTest {
    @isTest
    static void testDeleteEvents(){
        List<Event__c> eventsToDelete = new List<Event__c>();
        for (Integer i = 0; i < 200; i++) {
             Event__c event = new Event__c();
             event.Name__c = 'Test Event ' + i;
             event.Start__c = Date.today().addMonths(-3);
             event.End__c = Date.today().addMonths(-2);
             event.Live__c = true;
             eventsToDelete.add(event);
        }
        insert eventsToDelete;
        Test.startTest();
        DeleteEventBatch batch = new DeleteEventBatch();
        Database.executeBatch(batch);
        Test.stopTest();
        
        List<Event__c> remainingEvents = [SELECT Id FROM Event__c];
        System.assertEquals(0, remainingEvents.size(),'Expected Remaining Size is equal to Actual Remaining Size.');
        List<EmailMessage> sentEmails = [SELECT Id, ToAddress FROM EmailMessage WHERE Subject = 'Batch Job Completed'];
        System.assertEquals(1, sentEmails.size(),'Expected Size is equal to Actual Size.');
        System.assertEquals('ashutosh.singh@mirketa.com', sentEmails[0].ToAddress,'Expected Address is matched with Actual Address.');
    }
}